# Generated by Django 3.0.3 on 2020-05-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='state_name',
            field=models.CharField(default='n/a', max_length=30),
        ),
    ]
